baseurl: /jekyll-multilanguage
include: ['_pages']
exclude: ['README.md']

sass:
  sass_dir: _scss
  style: :compressed

# permalink: /:categories/:title/

defaults:
  - scope:
      path: _pages/en
      type: pages
    values:
      lang: en
  - scope:
      path: _pages/ua
      type: pages
    values:
      lang: ua
  - scope:
      path: _pages/ru
      type: pages
    values:
      lang: ru
  - scope:
      path: _posts/en
      type: posts
    values:
      lang: en
  - scope:
      path: _posts/ua
      type: posts
    values:
      lang: ua
  - scope:
      path: _posts/ru
      type: posts
    values:
      lang: ru
