baseurl: /jekyll-multilanguage

source:       ./jekyll
layouts_dir:  ./jekyll
data_dir:     ./jekyll
includes_dir: ./jekyll

# destination: ./public

exclude: ['README.md']

sass:
  sass_dir: _scss
  style: :compressed

# l10n
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/ua
    values:
      layout: default
      lang: ua
  -
    scope:
      path: _posts/ru
    values:
      layout: default
      lang: ru

